/*
 * nvm_address.h
 *
 *  Created on: 21 sep. 2025
 *      Author: Ludo
 */

#ifndef __NVM_ADDRESS_H__
#define __NVM_ADDRESS_H__

#include "sigfox_types.h"

/*!******************************************************************
 * \enum NVM_address_t
 * \brief NVM address mapping.
 *******************************************************************/
typedef enum {
    // Sigfox library.
    NVM_ADDRESS_SIGFOX_EP_ID = 0,
    NVM_ADDRESS_SIGFOX_EP_KEY = (NVM_ADDRESS_SIGFOX_EP_ID + SIGFOX_EP_ID_SIZE_BYTES),
    NVM_ADDRESS_SIGFOX_EP_LIB_DATA = (NVM_ADDRESS_SIGFOX_EP_KEY + SIGFOX_EP_KEY_SIZE_BYTES),
    // Device timings.
    NVM_ADDRESS_MONITORING_PERIOD_MINUTES = (NVM_ADDRESS_SIGFOX_EP_LIB_DATA + SIGFOX_NVM_DATA_SIZE_BYTES),
    NVM_ADDRESS_AIR_QUALITY_PERIOD_MINUTES = (NVM_ADDRESS_MONITORING_PERIOD_MINUTES + 2),
    NVM_ADDRESS_ACCELEROMETER_BLANKING_TIME_SECONDS = (NVM_ADDRESS_AIR_QUALITY_PERIOD_MINUTES + 2),
    // LED configuration.
    NVM_ADDRESS_LED_COLOR_TEMPERATURE_HUMIDITY_READING = (NVM_ADDRESS_ACCELEROMETER_BLANKING_TIME_SECONDS + 2),
    NVM_ADDRESS_LED_COLOR_SIGFOX_UPLINK,
    NVM_ADDRESS_LED_COLOR_SIGFOX_DOWNLINK,
    NVM_ADDRESS_LED_COLOR_AIR_QUALITY_READING,
    NVM_ADDRESS_LED_COLOR_ACCELEROMETER_READING,
} NVM_address_t;

#endif /* __NVM_ADDRESS_H__ */
